on:
  push:
    tags:
      - v*

jobs:
  test-and-lint:
    uses: ./.github/workflows/run-tests.yaml
  deploy:
    needs:
      - test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build package
        run: |
          pip install --upgrade build
          python -m build
      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
